bookingApp/urls.py
from django.urls import path
from .views import index,Booking_view,Room_details_view,booking_list,delete_booking,contact,search_room_category,gen_pdf,PayPalPaymentView,list_rooms,list_free_booking_room
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('',index,name='index'),
    path("rooms/", list_rooms, name="list_rooms"),
    path('booking/',Booking_view.as_view(),name='Booking_view'),
    path('booking_list/',booking_list,name='booking_list'),
    path('RoomDetails/<int:id>',Room_details_view.as_view(),name='roomDetails'),
    path('delete_booking/<int:id_booking>',delete_booking,name='delete_booking'),
    path("services/",TemplateView.as_view(template_name='services.html'),name='services'),
    path("about/",TemplateView.as_view(template_name='about.html'),name='about'),
    path('conatct/',contact,name="contact"),
    path('search_room_category/<str:category>', search_room_category, name='search_room_category'),
    path('list_free_booking_room/',list_free_booking_room,name='list_free_booking_room'),
    path('gen_pdf/<int:booking_id>/',gen_pdf,name="gen_pdf"),
    path('paypal_payment/<int:temp_booking_id>/',PayPalPaymentView.as_view(),name="payment_success")
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)

bookingProject/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'),name="accounts"),
    path('',include('bookingApp.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),
]

bookingApp/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.



class Category(models.Model):
    name_category = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.name_category}'

class Room(models.Model):
    category_room = models.ForeignKey(Category,on_delete=models.CASCADE)
    space = models.DecimalField(max_digits=10,decimal_places=2)
    beds = models.IntegerField(default=1)
    bath = models.IntegerField(default=1) 
    adult = models.IntegerField(default=1)
    child = models.IntegerField(default=0)
    description = models.TextField(max_length=10000,blank=True)
    image_room = models.ImageField(upload_to='media')
    price_per_night = models.DecimalField(max_digits=10,decimal_places=2,null=False)
    is_available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'category :{self.category_room} {self.space} m2, beds : {self.beds}'



class RoomImages(models.Model):
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media')

    def __str__(self):
        return f'image for the Room with id : {self.room.id}'

class Booking(models.Model):

    user= models.ForeignKey(User,on_delete=models.CASCADE)
    room= models.ForeignKey(Room,on_delete=models.CASCADE)
    name = models.CharField(max_length=255,null=False)
    phone_number = PhoneNumberField(blank=False,null=False)
    date_enter= models.DateTimeField(blank=True)
    date_out= models.DateTimeField(blank=True)
    total= models.DecimalField(max_digits=10,decimal_places=2)
    is_paied= models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    
    # def total(self):
    #     return self.appart.price_per_night * (self.date_out-self.date_enter)

    def __str__(self):
        return f"{self.user} book room \n {self.room.id} {self.room.price_per_night} DA \n date_in {self.date_enter} \nand the date of out is {self.date_out} \n and the total for the stay is : {self.total} DA"

    
    
class TempBooking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    name = models.CharField(max_length=255,null=False)
    phone_number = PhoneNumberField(blank=False,null=False)
    date_enter = models.DateField()
    date_out = models.DateField()
    total = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    is_paid = models.BooleanField(default=False)


class Contact(models.Model):
    first_name = models.CharField(max_length=255)
    last_name= models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    message = models.TextField()


class CommentRoom(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    comment = models.TextField()
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta : 
        ordering = ['-created_on']

    def __str__(self):
        return f'{self.created_on} Comment from {self.user} in the room {self.room.id}, comment is {self.comment}'

bookingApp/forms.py
from django import forms
from django.conf import settings
from .models import CommentRoom
from django.utils.html import format_html
from paypal.standard.forms import PayPalPaymentsForm
from phonenumber_field.formfields import PhoneNumberField

class AvailabilityForm(forms.Form):

    # appart_list =forms.ModelChoiceField(queryset=Appartment.objects.all(),empty_label="select_appartement")
    name=forms.CharField(max_length=255)
    phone_number=PhoneNumberField()
    check_in = forms.DateTimeField(required=True,input_formats=['%Y-%m-%d %H:%M'],widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    check_out = forms.DateTimeField(required=True,input_formats=["%Y-%m-%d %H:%M"],widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))


class SeachAvailableRoom(forms.Form):
    adult = forms.DecimalField(required=True)
    child= forms.DecimalField(required=True)
    check_in = forms.DateTimeField(required=True, input_formats=['%Y-%m-%dT%H:%M'])
    check_out = forms.DateTimeField(required=True, input_formats=['%Y-%m-%dT%H:%M'])


class PaymentMethodForm(forms.Form):
    CHOICES = [('pay_on_hotel','Pay on the Hotel'),('paypal_payment','Pay With paypal')]
    payment_method = forms.CharField(label="method_payment",widget=forms.RadioSelect(choices=CHOICES))

class ContactForm(forms.Form):
    first_name= forms.CharField(max_length=255)
    last_name= forms.CharField(max_length=255)
    email = forms.EmailField(max_length=255)
    message = forms.CharField(widget=forms.Textarea)



class CustomPayPalPaymentsForm(PayPalPaymentsForm):
    def get_image(self):
        return ''  # Return an empty string since we're not using an image
    

    def get_endpoint(self):
        if settings.PAYPAL_TEST:
            return "https://www.sandbox.paypal.com/cgi-bin/webscr"
        return "https://www.paypal.com/cgi-bin/webscr"
    

    def render(self):
        return format_html(
            u"""<form action="{0}" method="post">
                    {1}
                    <button type="submit" class="btn-pay">Pay the booking</button>
                </form>""",
            self.get_endpoint(),
            self.as_p()
        )


class CommentRoomForm(forms.ModelForm):
    class Meta : 
        model = CommentRoom
        fields = ['comment']
        widgets={
            'comment':forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder':'Leave a comment',
                    'id':'commentTextArea'
                    }
                    )
            
        }

bookingApp/views.py
from django.conf import settings
from django.shortcuts import render,redirect,HttpResponse,get_object_or_404
from .models import Booking, Room,Contact,TempBooking,CommentRoom,Category
from .forms import AvailabilityForm,ContactForm,PaymentMethodForm,CustomPayPalPaymentsForm,CommentRoomForm,SeachAvailableRoom
from django.urls import reverse
from django.views.generic import ListView,FormView,View
from .booking_function import availability
from django.contrib import messages


from django.templatetags.static import static

from django.template.loader import get_template
from xhtml2pdf import pisa


from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from datetime import datetime
from django.utils import timezone
import pytz

# Create your views here.



def index(request):
    room = Room.objects.all()
    categories = Category.objects.all()

    context={
        'category':categories,
        'rooms': room,
    }
    return render(request,'index.html',context)


def list_rooms(request):
    room = Room.objects.all()

    context={
        'rooms':room
    }

    return render(request,'rooms.html',context)


def booking_list(request):   
    if request.user.is_staff : 
        booking_list = Booking.objects.all()
        
        
    else : 
        booking_list = Booking.objects.filter(user = request.user)
    
    
    paris_tz = pytz.timezone('Europe/Paris')
    today = timezone.now().astimezone(paris_tz)
    context={
        'booking_list':booking_list,
        'now':today
    }

    return render(request,"booking_list.html",context)

def search_room_category(request,category):
    cat_room = Room.objects.filter(category_room__name_category__icontains=category)
    context={
        'categories_room':cat_room,
        'category_name':category,
    }
    return render(request,'search_rooms.html',context)



def delete_booking(request,id_booking):

    if request.user.is_staff : 
        del_booking = Booking.objects.get(id=id_booking)
        del_booking.room.is_available = True
        del_booking.room.save()
        del_booking.delete()

    else : 
        del_booking = Booking.objects.get(id=id_booking)
        del_booking.room.is_available = True
        del_booking.room.save()
        del_booking.delete()

    return redirect("booking_list")



def contact(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            f_name = form['first_name'].value()
            l_name = form['last_name'].value()
            email = form['email'].value()
            message = form['message'].value()
            contact = Contact.objects.create(
                first_name = f_name,
                last_name = l_name,
                email = email,
                message = message,
            )
            contact.save()
            messages.success(request,"Your Message was send with success")
            return redirect("index")
        
        else : 
            messages.error(request, "There was an error. Please try again.")
    else : 
        form = ContactForm()

    context ={
        'form' : ContactForm()
    }

    return render(request,'contact.html',context)



class RoomListView(ListView):
    model = Room


# def appart_details(request,id:int):
#     appart_id = get_object_or_404(Appartment,id=id)
#     context={
#         'appart_id':appart_id,
#     }

#     return render(request,'appart_details.html',context)


class Room_details_view(View):
    def get(self, request, *args, **kwargs):
        room_id = self.kwargs.get('id', None)
        room = get_object_or_404(Room, id=room_id)
        comments = CommentRoom.objects.filter(room = room)
        form = AvailabilityForm()

        formComment = CommentRoomForm()

        if room:
            context = {
                'room_id': room,
                'form': form,
                'comments':comments,
                'formComment' : formComment,

            }
            return render(request, "room_details.html", context)
        else:
            return HttpResponse("The Room does not exist!")

    def post(self, request, *args, **kwargs):
        room_id = self.kwargs.get('id', None)
        room_list = Room.objects.filter(id=room_id)
        available_room = []
        form = AvailabilityForm(request.POST)
        payment_method_form = PaymentMethodForm(request.POST)

        formComment = CommentRoomForm(request.POST)
        room = get_object_or_404(Room, id=room_id)
        if formComment.is_valid():
            comment = formComment.save(commit=False)
            comment.user = self.request.user
            comment.room= room 
            comment.save()
            return redirect('roomDetails',id=room_id)

        if form.is_valid() and payment_method_form.is_valid():
            payment_method_chose = payment_method_form.cleaned_data['payment_method']
            data = form.cleaned_data
    
            for room in room_list:
                if availability.booking_logic(room, data['check_in'], data['check_out']):
                    available_room.append(room)


            paris_tz = pytz.timezone('Europe/Paris')
            today = timezone.now().astimezone(paris_tz)

            name = data['name']
            phone_number = data['phone_number']
            check_in = data['check_in']
            check_out = data['check_out']

            print(f'check_in : {check_in.month}')
            print(f'check out : {check_out.month}')
            print(f'today : {today}')

            if self.request.user.is_authenticated:  

                if check_out < check_in:
                    return HttpResponse('Invalid Booking, The Date in should be less then the Date out, So please try again.')
                
                if check_in < today or check_out < today:
                    return HttpResponse('Invalid Booking, Date In and Date Out should be greater than or equal to today. Please try again.')


                if len(available_room) > 0:
                    room = available_room[0]
                    num_days = (data['check_out'] - data['check_in']).days
                    total_cost_room = room.price_per_night * num_days

                    if payment_method_chose == 'pay_on_hotel':
                        booking = Booking.objects.create(
                            user=self.request.user,
                            room=room,
                            name=name,
                            phone_number = (phone_number),
                            date_enter=data['check_in'],
                            date_out=data['check_out'],
                            total=total_cost_room,
                        )
                        self.complete_booking(booking, room)
                        
                        return render(request, 'validation_booking.html', {'booking': booking})
                    else:
                        temp_booking = TempBooking.objects.create(
                            user=self.request.user,
                            room=room,
                            name=name,
                            phone_number =(phone_number),
                            date_enter=data['check_in'],
                            date_out=data['check_out'],
                            total=total_cost_room,
                        )
                        total_amount_for_booking = temp_booking.total / 220
                        total_amount_for_booking_in_usd = str(total_amount_for_booking)
                        host = request.get_host()
                        paypal_dict = {
                            "business": settings.PAYPAL_RECEIVER_EMAIL,
                            "amount": total_amount_for_booking_in_usd,
                            "item_name": f"room_id : {temp_booking.room.id}",
                            "invoice": str(temp_booking.id),
                            'currency_code': 'USD',
                            "notify_url": f'http://{host}{reverse("paypal-ipn")}',
                            "return": f'http://{host}{reverse("payment_success", args=[temp_booking.id])}',
                            "cancel_return": f'http://{host}{reverse("index")}',
                        }
                        form = CustomPayPalPaymentsForm(initial=paypal_dict)
                        context = {
                            "form_paypal": form,
                            "booking": temp_booking,
                            'formComment':formComment,
                        }
                        return render(request, "paypal-payment.html", context)
                else:
                    return HttpResponse(f"This room is not available from {data['check_in']} to {data['check_out']}.")
            else:
                messages.warning(request, 'You should login before booking. Please login and then book.')
                return redirect('account_login')
        else:
   
            context = {
                'room_id': room_id,
                'form': form,
                'payment_method_form': payment_method_form,
                'formComment' : formComment,

            }
            return render(request, "room_details.html", context)

    def complete_booking(self, booking, room):
        booking.save()
        room.is_available = False
        print(f'room avivalability : {room.is_available}')
        room.save()

        
def list_free_booking_room(request):
    if request.method == 'POST':
        form = SeachAvailableRoom(request.POST)
        if not form.is_valid():
            print(form.errors)
            print('Raw POST data:', request.POST)
        if form.is_valid():
            data = form.cleaned_data
            adult = data['adult']
            child = data['child']
            check_in = data['check_in']
            check_out = data['check_out']
            
            list_available_rooms = []

bookingApp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="Boutiche Youcef" content="colorlib.com">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/details_page.css' %}" />
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>


    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">  
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    
    <!-- Libraries Stylesheet -->
    <link href=" {% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% include "header.html" %} 
    {% block content %}{% endblock content %}
    {% include "newsletter.html" %}
    {% include 'footer.html' %}
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/script.js' %}"></script>
  </div>
    
</body>
</html>

bookingApp/templates/booking.html
{% extends "base.html" %}

{% load static %}

{% block title %}Booking{% endblock title %}

{% block content %}
    <form action = "" method = "POST">
        {% csrf_token %} 
        {{ form.as_p }}

        <button type="submit">Submit</button>

    </form>
{% endblock content %}

bookingApp/templates/booking_list.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/booking_list_view.css' %}">


{% block title %}My Booking List{% endblock title %}

{% block content %}
    <div class="row row-cols-1 row-cols-md-3 g-3 mt-2 px-2">
        {% for booking in booking_list  %}        
            <div class="col">
                <div class="card">
                    <img src="{{ booking.room.image_room.url }}" class="card-img-top px-2 py-2" alt="image room" >
                    <div class="card-body">
                        <h5 class="card-title"><strong>Room ID:</strong> {{booking.room.id}}</h5>
                        <p class="card-text"><strong>Name:</strong> {{ booking.name }}</p>
                        <p class="card-text"><strong>Phone Number:</strong> {{ booking.phone_number }}</p>
                        <p class="card-text"><strong>Date IN:</strong> {{ booking.date_enter }}</p>
                        <p class="card-text"><strong>Date Out:</strong> {{ booking.date_out }}</p>
                        <p class="card-text"><strong>Bed(s):</strong> {{ booking.room.beds }}</p>
                        <p class="card-text"><strong>Bath(es):</strong> {{ booking.room.bath }}</p>
                        <p class="card-text"><strong>Price Per night</strong>: {{ booking.room.price_per_night }} DA</p>
                        <p class="card-text"><strong>Total:</strong> {{ booking.total }} DA</p>
                        {% if booking.is_paied %}
                            <p class="card-text"><strong>Paied</strong></p>

                        {% else %}
                            <p class="card-text"><strong>NOT PAIED</strong></p>
                        {% endif %}
                        {% if booking.date_out > now  %}
                            <p class="card-text"><a href="{% url 'delete_booking' booking.id %}" class="btn btn-danger" onclick="return confirm('Are Your sure you want to cancel the booking')">Cancel The Booking</a></p>
                            <p class ="card-text"><a href="{% url 'gen_pdf' booking.id %}" class="btn btn-success">Download the PDF</a></p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %}

bookingApp/templates/cancel_booking.html
{% extends "base.html" %}

{% load static %}

{% block title %}Cancel Booking {{ user }} Num {{ del_booking.id }} {% endblock title %}



{% block content %}

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'index' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{del_booking.appart.satet}}</h1>
                <p>Are You sure you want to delete this booking</p>

                <a href="{% url 'delete_booking' del_booking.id %}" class="btn btn-danger">DETELE BOOKING</a>
            </div>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->



{% endblock  %}

bookingApp/templates/room_details.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %} Details Room {{ room_id.id }}{% endblock title %}



{% block content %}

    <div class="card-wrapper-appart container">
        <div class="card card-appart-details">
            <!-- card left -->
            <div class="appart-imgs">
                <div class="img-display">
                    
                    <div class="img-showcase">
                        {% for img in room_id.roomimages_set.all %}
                            <img src="{{ img.image.url }}" alt="image">
                        {% endfor %}
                    </div>
                </div>
                <div class="img-select">

                    {% for img in room_id.roomimages_set.all %} 
                        <div class="img-item">
                            <a href="#" data-id="{{ forloop.counter }}">
                                <img src="{{ img.image.url }}" alt="image">
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="vl"></div>
            <!-- card right -->
            <div class="appart-content">
                <h4 class="appart-title">Room ID: {{room_id.id}}</h4>
                <h2 class="mt-4">Category room: {{ room_id.category_room.name_category }}</h2>
                <div class="appart-detail">
                    <h6>About this Room:</h6>
                    <p>{{ room_id.description }}</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo eveniet veniam tempora fuga tenetur placeat sapiente architecto illum soluta consequuntur, aspernatur quidem at sequi ipsa!</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, perferendis eius. Dignissimos, labore suscipit. Unde.</p>
                </div>
                <div class="mb-3 d-flex justify-content-between">
                    <p class="card-text"><small class="border-end text-muted me-3 pe-3"><i class="fa fa-bed"></i> {{ room_id.beds }} bed(s)</small></p>
                    <p class="card-text"><small class="border-end text-muted me-3 pe-3"><i class="fa fa-bath"></i> {{ room_id.bath }} bath(es)</small></p>
                    <p class="card-text"><small class="border-end me-3 pe-3"><i class="fa fa-male me-2"></i>{{ room_id.adult }} adult</small></p>
                    <p class="card-text"><small class="text-muted me-3 pe-3"><i class="fa fa-child me-2"></i>{{ room_id.child }} child</p></small>
                </div>
                <div class="appart-price">
                    <p class="new-price">Price: <span>{{ room_id.price_per_night }} DA/Night</span></p>
                </div>
                <form role="form" method="POST" class="form-booking-details-page">
                    {% csrf_token %}
                    <div class="label-field-form">
                        {% for field in form  %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field|add_class:"form-control" }}
                                <div class="invalid-feedback">
                                    {{ field.error|striptags }}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <br/>
                    {% comment %} {{ form.as_p }} {% endcomment %}
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="payment_method" id="pay_on_hotel" checked value="pay_on_hotel">
                        <label class="form-check-label" for="flexRadioDefault2">
                          Pay when you arrive to the hotel.
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="payment_method" id="paypal_payment" value="paypal_payment">
                        <label class="form-check-label" for="flexRadioDefault1">
                          Pay with Paypal.
                        </label>
                    </div>
                    <br/>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            Book now 
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
    <div class="container" >
        <h4>Leave a Comment</h4>
        <form method="POST">  
            {% csrf_token %}
            {% for field_comment in formComment  %}
                {{ field_comment }}
            {% endfor %}
            
            <br/>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <br/>

    <div class="comment-div container">
        <h1>Comments</h1>
        {% for comment in comments %}
            <div class="comment-box border rounded p-3 mb-3">
                <div class="comment-header d-flex justify-content-between">
                    <h5 class="comment-user mb-1">{{ comment.user }}</h5>
                    <small class="text-muted">{{ comment.created_on|date:"F j, Y, g:i a" }}</small>
                </div>
                <div class="comment-body">
                    <p class="comment-text">{{ comment.comment }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
    <br/>
    <br/>
    <br/>
    <br/>

    <script>
        const imgs = document.querySelectorAll('.img-select a');
        const imgBtns = [...imgs];
        
        let imgId = 1;
    
        imgBtns.forEach((imgItem) => {
            imgItem.addEventListener('click', (event) => {
                event.preventDefault();
                imgId = imgItem.dataset.id;
                slideImage();
            });
        });
    
        function slideImage(){
            const displayWidth = document.querySelector('.img-showcase img:first-child').clientWidth;
            document.querySelector('.img-showcase').style.transform = `translateX(${- (imgId - 1) * displayWidth}px)`;
        }
    
        window.addEventListener('resize', slideImage);
    </script>
    

{% endblock content %}